In [6]:
# input_dir_dvv is the file location for dvv data folder
# input_dir_dv is the file location for dv data folder

import os
import pandas as pd
import string


input_dir_dvv='Chronus test/Cell C/DVV'
input_dir_dv='Chronus test/Cell C/DV'

dvv_files = [f for f in os.listdir(input_dir_dvv)]# if os.path.isfile(join(input_dir_dvv, f))]
dv_files = [f for f in os.listdir(input_dir_dv)]# if os.path.isfile(join(input_dir_dv, f))]
combined_df=pd.DataFrame()

for dvv_f, dv_f in zip(dvv_files, dv_files):
    if os.stat(input_dir_dvv +'/' +dvv_f).st_size == 0:
        print('File is empty')
    else:
        dvv_df = pd.read_csv(input_dir_dvv +'/' +dvv_f)
        dvv_df = dvv_df[["real_time_106999","real_data_106999","imag_data_106999"]]
        print('dvv len',len(dvv_df))
        if os.stat(input_dir_dv +'/' +dvv_f).st_size == 0:
            print('File is empty')
        else:
            dv_df = pd.read_csv(input_dir_dv + '/'+ dv_f)
            dv_df = dv_df[["real_data_27999999","imag_data_27999999"]]
            # Scaling the dv data to match the dvv data
            dv_df = dv_df.apply(lambda x: x * 10)
            print('dv len:',len(dv_df))

            # Use the combined df data to proceed with analysis. 
            combined_df_cvv_and_cv = pd.concat([dvv_df,dv_df], axis=1)
            combined_df=pd.concat([combined_df,combined_df_cvv_and_cv],axis=0)
combined_df=combined_df.sort_values(by='real_time_106999',ascending=True)

dvv len 96
dv len: 96
dvv len 1044
dv len: 1044
dvv len 148
dv len: 148
dvv len 95
dv len: 95
dvv len 129
dv len: 129
dvv len 152
dv len: 152
dvv len 95
dv len: 95
dvv len 121
dv len: 121
dvv len 129
dv len: 129
dvv len 92
dv len: 92
dvv len 128
dv len: 128
dvv len 132
dv len: 132
dvv len 100
dv len: 100
dvv len 113
dv len: 113
dvv len 145
dv len: 145
dvv len 84
dv len: 84
dvv len 128
dv len: 128
dvv len 148
dv len: 148
dvv len 89
dv len: 89
dvv len 119
dv len: 119
dvv len 140
dv len: 140
dvv len 97
dv len: 97
dvv len 128
dv len: 128
dvv len 156
dv len: 156
dvv len 89
dv len: 89
dvv len 112
dv len: 112
dvv len 151
dv len: 151
dvv len 84
dv len: 84
dvv len 124
dv len: 124
dvv len 497
dv len: 497
dvv len 100
dv len: 100
dvv len 111
dv len: 111
dvv len 140
dv len: 140
dvv len 88
dv len: 88
dvv len 137
dv len: 137
dvv len 156
dv len: 156
dvv len 97
dv len: 97
dvv len 140
dv len: 140
dvv len 148
dv len: 148
dvv len 88
dv len: 88
dvv len 120
dv len: 120
dvv len 156
dv len: 156
dvv len 84
dv 

dv len: 95
dvv len 105
dv len: 105
dvv len 103
dv len: 103
dvv len 92
dv len: 92
dvv len 105
dv len: 105
dvv len 156
dv len: 156
dvv len 105
dv len: 105
dvv len 105
dv len: 105
dvv len 95
dv len: 95
dvv len 100
dv len: 100
dvv len 100
dv len: 100
dvv len 105
dv len: 105
dvv len 105
dv len: 105
dvv len 100
dv len: 100
dvv len 100
dv len: 100
dvv len 95
dv len: 95
dvv len 92
dv len: 92
dvv len 105
dv len: 105
dvv len 92
dv len: 92
dvv len 92
dv len: 92
dvv len 97
dv len: 97
dvv len 108
dv len: 108
dvv len 103
dv len: 103
dvv len 92
dv len: 92
dvv len 108
dv len: 108
dvv len 97
dv len: 97
dvv len 103
dv len: 103
dvv len 132
dv len: 132
dvv len 96
dv len: 96
dvv len 92
dv len: 92
dvv len 100
dv len: 100
dvv len 105
dv len: 105
dvv len 105
dv len: 105
dvv len 103
dv len: 103
dvv len 108
dv len: 108
dvv len 96
dv len: 96
dvv len 103
dv len: 103
dvv len 96
dv len: 96
dvv len 140
dv len: 140
dvv len 96
dv len: 96
dvv len 103
dv len: 103
dvv len 105
dv len: 105
dvv len 100
dv len: 100
dvv len 1

dvv len 121
dv len: 121
dvv len 136
dv len: 136
dvv len 104
dv len: 104
dvv len 116
dv len: 116
dvv len 136
dv len: 136
dvv len 97
dv len: 97
dvv len 108
dv len: 108
dvv len 152
dv len: 152
dvv len 96
dv len: 96
dvv len 132
dv len: 132
dvv len 148
dv len: 148
dvv len 92
dv len: 92
dvv len 129
dv len: 129
dvv len 124
dv len: 124
dvv len 97
dv len: 97
dvv len 132
dv len: 132
dvv len 136
dv len: 136
dvv len 96
dv len: 96
dvv len 111
dv len: 111
dvv len 136
dv len: 136
dvv len 100
dv len: 100
dvv len 121
dv len: 121
dvv len 132
dv len: 132
dvv len 100
dv len: 100
dvv len 1319
dv len: 1319
dvv len 152
dv len: 152
dvv len 108
dv len: 108
dvv len 108
dv len: 108
dvv len 153
dv len: 153
dvv len 100
dv len: 100
dvv len 116
dv len: 116
dvv len 148
dv len: 148
dvv len 84
dv len: 84
dvv len 124
dv len: 124
dvv len 148
dv len: 148
dvv len 88
dv len: 88
dvv len 132
dv len: 132
dvv len 132
dv len: 132
dvv len 88
dv len: 88
dvv len 113
dv len: 113
dvv len 136
dv len: 136
dvv len 104
dv len: 104
dvv le

dvv len 153
dv len: 153
dvv len 96
dv len: 96
dvv len 108
dv len: 108
dvv len 164
dv len: 164
dvv len 100
dv len: 100
dvv len 124
dv len: 124
dvv len 132
dv len: 132
dvv len 100
dv len: 100
dvv len 129
dv len: 129
dvv len 153
dv len: 153
dvv len 96
dv len: 96
dvv len 120
dv len: 120
dvv len 132
dv len: 132
dvv len 100
dv len: 100
dvv len 116
dv len: 116
dvv len 132
dv len: 132
dvv len 92
dv len: 92
dvv len 128
dv len: 128
dvv len 145
dv len: 145
dvv len 100
dv len: 100
dvv len 132
dv len: 132
dvv len 140
dv len: 140
dvv len 100
dv len: 100
dvv len 132
dv len: 132
dvv len 156
dv len: 156
dvv len 97
dv len: 97
dvv len 132
dv len: 132
dvv len 156
dv len: 156
dvv len 100
dv len: 100
dvv len 124
dv len: 124
dvv len 160
dv len: 160
dvv len 100
dv len: 100
dvv len 124
dv len: 124
dvv len 137
dv len: 137
dvv len 95
dv len: 95
dvv len 132
dv len: 132
dvv len 137
dv len: 137
dvv len 97
dv len: 97
dvv len 124
dv len: 124
dvv len 169
dv len: 169
dvv len 100
dv len: 100
dvv len 116
dv len: 116
dvv 

## Run basic stats, check size , NAs and assign to new df

In [8]:

combined_df.describe()
# print(len(combined_df))
# combined_df.count()


# #combined_df.isna().count()
# combined_df_cell_A=combined_df
# combined_df_cell_B=combined_df
combined_df_cell_C=combined_df
# combined_df_Mixed1=combined_df
# combined_df_Mixed2=combined_df



### Create label column,combine all dfs together for training set 

In [9]:
combined_df_cell_A.shape
combined_df_cell_A['type']=1
combined_df_cell_B['type']=2
combined_df_cell_C['type']=3
combined_df_all_cells=pd.concat([combined_df_cell_A,combined_df_cell_B,combined_df_cell_C],axis=0)
combined_df_all_cells.shape

(1101253, 6)

In [10]:
combined_df_all_cells.to_csv('combined_df_all_cells.csv')

## Plot correlations 

In [11]:
import numpy as np
print(np.corrcoef(combined_df_all_cells.real_data_106999,combined_df_all_cells.imag_data_106999 ))
print(np.corrcoef(combined_df_all_cells.real_data_27999999,combined_df_all_cells.imag_data_27999999 ))
print(np.corrcoef(combined_df_all_cells.real_data_106999,combined_df_all_cells.real_data_27999999 ))
print(np.corrcoef(combined_df_all_cells.imag_data_106999,combined_df_all_cells.imag_data_27999999 ))


import matplotlib.pyplot as plt
fig= plt.figure()
fig.show()
plt.plot(combined_df_cell_A.real_time_106999,combined_df_cell_A.real_data_106999 )
plt.plot(combined_df_cell_A.real_time_106999,combined_df_cell_A.real_data_27999999 )

[[1.         0.98333851]
 [0.98333851 1.        ]]
[[ 1.         -0.87862299]
 [-0.87862299  1.        ]]
[[1.         0.93327677]
 [0.93327677 1.        ]]
[[ 1.         -0.95753296]
 [-0.95753296  1.        ]]


c:\python\python36\lib\site-packages\matplotlib\figure.py:459: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "


###  If time dependency is important , then we can only take similar time intervals by shifting towards the earliest and cut at the shortest set (didnt proceed with this idea later)


In [123]:
#######+++++++++++++++++time shift=========================

print(combined_df_cell_A.real_time_106999.min()) #1
print(combined_df_cell_B.real_time_106999.min()) #3
print(combined_df_cell_C.real_time_106999.min()) #2
delta_AA=combined_df_cell_A.real_time_106999.min()-combined_df_cell_A.real_time_106999.min()
delta_AB=combined_df_cell_B.real_time_106999.min()-combined_df_cell_A.real_time_106999.min()
delta_AC=combined_df_cell_C.real_time_106999.min()-combined_df_cell_A.real_time_106999.min()

combined_df_cell_A_shifted=combined_df_cell_A.copy()
combined_df_cell_B_shifted=combined_df_cell_B.copy()
combined_df_cell_C_shifted=combined_df_cell_C.copy()

combined_df_cell_A_shifted.real_time_106999=combined_df_cell_A_shifted.real_time_106999-delta_AA
combined_df_cell_B_shifted.real_time_106999=combined_df_cell_B_shifted.real_time_106999-delta_AB
combined_df_cell_C_shifted.real_time_106999=combined_df_cell_C_shifted.real_time_106999-delta_AC

print(combined_df_cell_A_shifted.real_time_106999.min()) 
print(combined_df_cell_B_shifted.real_time_106999.min()) 
print(combined_df_cell_C_shifted.real_time_106999.min()) 

print(combined_df_cell_A_shifted.real_time_106999.max()) #3
print(combined_df_cell_B_shifted.real_time_106999.max()) #1
print(combined_df_cell_C_shifted.real_time_106999.max()) #2

combined_df_cell_A_shifted=combined_df_cell_A_shifted[combined_df_cell_A_shifted['real_time_106999']<(combined_df_cell_B_shifted.real_time_106999.max())]
combined_df_cell_C_shifted=combined_df_cell_C_shifted[combined_df_cell_C_shifted['real_time_106999']<(combined_df_cell_B_shifted.real_time_106999.max())]

print(combined_df_cell_A_shifted.real_time_106999.max()) 
print(combined_df_cell_B_shifted.real_time_106999.max()) 
print(combined_df_cell_C_shifted.real_time_106999.max()) 

print(combined_df_cell_B_shifted.shape)


fig= plt.figure()
fig.show()
plt.plot(combined_df_cell_A.real_time_106999,combined_df_cell_A.real_data_106999 )
plt.plot(combined_df_cell_B_shifted.real_time_106999,combined_df_cell_B_shifted.real_data_106999 )

fig= plt.figure()
plt.plot(combined_df_cell_A.real_time_106999,combined_df_cell_A.real_data_27999999 )
plt.plot(combined_df_cell_B_shifted.real_time_106999,combined_df_cell_B_shifted.real_data_27999999 )


0.00922
0.017044999999999998
0.0128925
0.00922
0.00922
0.00922
9.9987875
9.991475000000001
9.9942575
9.982635
9.991475000000001
9.988417499999999
(389250, 6)


### I assume time column is needed only for the indexing so i ignore it for training.
### Prepare data for training, converting labels
 take only 4 columns (to time dependency) 

In [23]:
from sklearn.model_selection import train_test_split
X=combined_df_all_cells[['real_data_106999','imag_data_106999','real_data_27999999','imag_data_27999999']]
y=combined_df_all_cells['type']
# y=pd.get_dummies(y,columns=['type'])

from sklearn.preprocessing import StandardScaler
scalerX = StandardScaler().fit(X)

X_scaled = scalerX.transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y,
                                                    test_size=0.30,
                                                    random_state=1)
# only will test 
X_mix=combined_df_Mixed1[['real_data_106999','imag_data_106999','real_data_27999999','imag_data_27999999']]
scalerX_mix = StandardScaler().fit(X_mix)
X_mix = scalerX_mix.transform(X_mix)


# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)


### use SVM classifier with grid search for finding hyperparameters and use the best results

In [18]:
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV

# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]}]



scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(
        svm.SVC(), tuned_parameters, cv=3, scoring='%s_macro' % score
    )
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()

    



# Tuning hyper-parameters for precision



ValueError: bad input shape (146833, 3)

### Summarize best results (hyperparameters) and use them for final model 

In [ ]:

grid_result=clf.fit(X_train, y_train)
best_params = grid_result.best_params_
print(best_svr)

clf = svm.SVC(best_params,probability=True)
clf.fit(X_train, y_train)

# Scores
print('training accuracy:{}'.format(clf.score(X_train, y_train)))

# y_pred=rf.predict(X_test)
print('testing accuracy:{}'.format(clf.score(X_test, y_test)))

### Use trained model to predict classes and their probabilities with mixed set

In [ ]:

results = clf.predict_proba(X_mix)[0]

# gets a dictionary of {'class_name': probability}
prob_per_class_dictionary = dict(zip(model.classes_, results))

# gets a list of ['most_probable_class', 'second_most_probable_class', ..., 'least_class']
results_ordered_by_probability = map(lambda x: x[0], sorted(zip(model.classes_, results), key=lambda x: x[1], reverse=True))

### transorm original data back and add original columns of index (=time) and new column of probability results


In [ ]:
X_mix_restored=scalerX_mix.inverse_transform(X_mix)
ready_results=pd.concat([combined_df_Mixed1['real_time_106999'],X_mix_restored,results_ordered_by_probability],axis=1)